### ISSUE TITLE
icons not working properly

### ISSUE THREAD

**Issue by davidpaulos** [gapan/xdgmenumaker#13]
several icon themes dont work with the xdgmenumaker in jwm
like numix for example besides being the selected icon theme the icons showed are the gnome default one

**Comment by gapan** [comment]
OK, so JWM can apparently use SVG icons now and the numix icon set only includes SVG icons. The above commit should fix this.

Thanks for the report!

**Comment by davidpaulos** [comment]
thanks i can confirm it works now
