### ISSUE TITLE
add support for amiwm?

### ISSUE THREAD

**Issue by alexmyczko** [gapan/xdgmenumaker#15]
I have tried something, but it's probably much better done by you with xdgmenumaker:

http://sid.ethz.ch/menu/

**Comment by gapan** [comment]
Yes, I can certainly do that! Can you pull from master and test it? Documentation is pending but just run with "-f amiwm".

Do you really need separators between menu categories?

**Comment by alexmyczko** [comment]
Checked out, tried. Worked (well the output of it looks fine), I haven't launched amiwm to check how it looks. And noticed, not many people use it: https://repology.org/metapackage/xdgmenumaker/versions

**Comment by gapan** [comment]
Oh, I've tried it in amiwm myself. I've just added the necessary documentation and tagged version 1.5. Thanks for the suggestion.
