### ISSUE TITLE
Compton shadow and xdgmenumaker

### ISSUE THREAD

**Issue by arcolinuxz** [gapan/xdgmenumaker#18]
Can you tell me the class I should use in compton to get shadow effect on the menu?
Or the name?
`    "name *= 'compton'",
    "name *= 'Chromium'",
    "name *= 'Chrome'",
    "class_g = 'Firefox' && argb",
    "class_g = 'Conky'",
    "class_g = 'Kupfer'",`

**Comment by gapan** [comment]
I'm sorry, but I think you have the wrong project. xdgmenumaker does not create any window by itself. It just supplies contents for menus that window managers show.
