### ISSUE TITLE
I have changed makefile... now works with checkinstall, and better uninstall

### ISSUE THREAD

**Issue by vitforlinux-gimp** [gapan/xdgmenumaker#26]
PREFIX ?= /usr/local
DESTDIR ?= /

man:
	@echo "Generating manpage..."
	@txt2tags -o man/xdgmenumaker.1 man/xdgmenumaker.t2t || \
		echo "WARNING: txt2tags is not installed. The xdgmenumaker manpage will not be created."

install:
	install -d -m 755 $(DESTDIR)/$(PREFIX)/bin
	install -m 755 src/xdgmenumaker $(DESTDIR)/$(PREFIX)/bin/xdgmenumaker
	install -d -m 755 $(DESTDIR)/$(PREFIX)/share/desktop-directories
	install -m 644 desktop-directories/* $(DESTDIR)/$(PREFIX)/share/desktop-directories
	if [ -f man/xdgmenumaker.1 ]; then \
		install -d -m 755 $(DESTDIR)/$(PREFIX)/share/man/man1; \
		install -m 644 man/xdgmenumaker.1 $(DESTDIR)/$(PREFIX)/share/man/man1/; \
	fi
	sed "s|^prefix = 'not_set'|prefix = '$(PREFIX)'|" src/xdgmenumaker > $(DESTDIR)/$(PREFIX)/bin/xdgmenumaker
	#chmod 755 $(DESTDIR)/$(PREFIX)/bin/xdgmenumaker

clean: test-clean
	rm -f man/xdgmenumaker.1

test:
	$(MAKE) -C tests/

test-clean:
	$(MAKE) clean -C tests/

uninstall:
	rm -f $(DESTDIR)/$(PREFIX)/bin/xdgmenumaker
	rm -f $(DESTDIR)/$(PREFIX)/share/desktop-directories/xdgmenumaker*
	rm -f $(DESTDIR)/$(PREFIX)/share/man/man1/xdgmenumaker.1

.PHONY: man clean install uninstall test test-clean

**Comment by gapan** [comment]
I'm sorry, but I can't accept this like this. If you'd like, reopen and just list the changes that you made. It would be **much** preferable to do a proper pull request though.

**Comment by vitforlinux-gimp** [comment]
Sorry, I found it excessive to make a fork to add two lines to the make file... and thus be able to make a deb package, which I have now done.
