### ISSUE TITLE
Syntax warning with python 3.12

### ISSUE THREAD

**Issue by sunshine69** [gapan/xdgmenumaker#27]
Ubuntu 24.04 python 3.12.3

xdgmenumaker -n -i -f jwm
/usr/local/bin/xdgmenumaker:563: SyntaxWarning: invalid escape sequence '\)'
  name = app.name.decode().replace(')', '\)')

Looks ike this python version it thinks the \ is the escape char even string quote using '

I just put the r into it and it is quiet. Trying to make a PR but somehow does not see the fork button .

soemthing like this on line 563
```
name = app.name.decode().replace(')', r'\)')
```

**Comment by sunshine69** [comment]
Just see the fork button - PR created

**Comment by gapan** [comment]
PR merged, thanks!
